site_name: PolMethods

theme:
  name: material
  language: en
  logo: assets/logo.png 
  features: 
  - navigation.tabs
  - navigation.sections
  - toc.integrate
  - navigation.top
  - search.suggest
  - search.highlight
  - content.tabs.link 
  - content.code.anotation 
  - content.code.copy
  palette: 
    # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
    # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default 
    toggle: 
      icon: material/weather-night 
      name: Switch to dark mode
    primary: blue grey
    accent: amber 
    # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate 
    toggle: 
      icon: material/weather-sunny
      name: Switch to light mode 
    primary: blue grey
    accent: lime 

copyright: |
  &copy; 2023 <a href="https://github.com/sophiemainz"  target="_blank" rel="noopener">Sophie Mainz</a>


  


    


